In [3]:
import numpy as np
import pandas as pd

In [4]:
label = [1,2,3]
my_list = [10,20,30]
arr = np.array(['a','b','c'])
d = {1:10,2:40,3:90}

In [5]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [6]:
pd.Series(my_list,index = label)

1    10
2    20
3    30
dtype: int64

In [7]:
pd.Series(d)

1    10
2    40
3    90
dtype: int64

In [8]:
data_list = {
  "Name" : ["bhoomi","sonam","sanjeev","ayush","parth","payal"],
  "Age" : [18,42,50,23,19,20],
  "salart" :[200000000,30000000000,400000000000,5000000000000000,230000000,1200000000],
 }
pd.DataFrame(data_list)

      Name  Age            salart
0   bhoomi   18         200000000
1    sonam   42       30000000000
2  sanjeev   50      400000000000
3    ayush   23  5000000000000000
4    parth   19         230000000
5    payal   20        1200000000

In [9]:
data_set = [
    ["bhoomi",12,20000000000000],
    ["sonam",42,20000000000000000],
    ["sanjeev",52,3444444444444444],
    ["ayush",23,400000000000000000000000]
]
df = pd.DataFrame(data_set)
columns = ["Name","Age","salary"]
df = pd.DataFrame(data_set,columns=columns)
df

      Name  Age                    salary
0   bhoomi   12            20000000000000
1    sonam   42         20000000000000000
2  sanjeev   52          3444444444444444
3    ayush   23  400000000000000000000000

In [10]:
df

      Name  Age                    salary
0   bhoomi   12            20000000000000
1    sonam   42         20000000000000000
2  sanjeev   52          3444444444444444
3    ayush   23  400000000000000000000000

In [11]:
df["Name"]

0     bhoomi
1      sonam
2    sanjeev
3      ayush
Name: Name, dtype: str

In [17]:
df[["Name","Age"]]

      Name  Age
0   bhoomi   12
1    sonam   42
2  sanjeev   52
3    ayush   23

In [12]:
df["profession"] = ["teach","doct","eng","mech"]

In [13]:
df

      Name  Age                    salary profession
0   bhoomi   12            20000000000000      teach
1    sonam   42         20000000000000000       doct
2  sanjeev   52          3444444444444444        eng
3    ayush   23  400000000000000000000000       mech

In [14]:
df.drop("profession",axis=1)

      Name  Age                    salary
0   bhoomi   12            20000000000000
1    sonam   42         20000000000000000
2  sanjeev   52          3444444444444444
3    ayush   23  400000000000000000000000

In [ ]:
df  #profession col is still there bcz we did n't delete it from original ram or place
#to delete permanently use inplace = true

      Name  Age                    salary profession
0   bhoomi   12            20000000000000      teach
1    sonam   42         20000000000000000       doct
2  sanjeev   52          3444444444444444        eng
3    ayush   23  400000000000000000000000       mech

In [16]:
df.drop("profession",axis=1,inplace= True)

In [17]:
df

      Name  Age                    salary
0   bhoomi   12            20000000000000
1    sonam   42         20000000000000000
2  sanjeev   52          3444444444444444
3    ayush   23  400000000000000000000000

In [19]:
df.loc[0]

Name              bhoomi
Age                   12
salary    20000000000000
Name: 0, dtype: object

In [20]:
df["Name"]

0     bhoomi
1      sonam
2    sanjeev
3      ayush
Name: Name, dtype: str

In [21]:
df

      Name  Age                    salary
0   bhoomi   12            20000000000000
1    sonam   42         20000000000000000
2  sanjeev   52          3444444444444444
3    ayush   23  400000000000000000000000

In [25]:
df.loc[0:1][["Name","Age"]]

     Name  Age
0  bhoomi   12
1   sonam   42

In [26]:
df["Age"] > 12

0    False
1     True
2     True
3     True
Name: Age, dtype: bool

In [27]:
df[df["Age"]>12]

      Name  Age                    salary
1    sonam   42         20000000000000000
2  sanjeev   52          3444444444444444
3    ayush   23  400000000000000000000000

In [32]:
df1 ={
    "A" : [1,2,np.nan,7,8],
    "B" : [6,8,2,np.nan,np.nan],
    "C" : [4,np.nan,2,np.nan,9],
    "D" : [9,3,8,1,0] 
}
df1 = pd.DataFrame(df1)

In [34]:
df1

     A    B    C  D
0  1.0  6.0  4.0  9
1  2.0  8.0  NaN  3
2  NaN  2.0  2.0  8
3  7.0  NaN  NaN  1
4  8.0  NaN  9.0  0

In [35]:
df1.isna().sum()

A    1
B    2
C    2
D    0
dtype: int64

In [36]:
df1.dropna()

     A    B    C  D
0  1.0  6.0  4.0  9

In [39]:
df1.dropna(thresh=3)

     A    B    C  D
0  1.0  6.0  4.0  9
1  2.0  8.0  NaN  3
2  NaN  2.0  2.0  8
4  8.0  NaN  9.0  0

In [40]:
df1.fillna(0)

     A    B    C  D
0  1.0  6.0  4.0  9
1  2.0  8.0  0.0  3
2  0.0  2.0  2.0  8
3  7.0  0.0  0.0  1
4  8.0  0.0  9.0  0

In [43]:
values = {"A" :100,"B" :345,"C" :333,"D" :123}
df1.fillna(value= values)

       A      B      C  D
0    1.0    6.0    4.0  9
1    2.0    8.0  333.0  3
2  100.0    2.0    2.0  8
3    7.0  345.0  333.0  1
4    8.0  345.0    9.0  0

In [44]:
students = pd.DataFrame({
    "Student_ID": [101, 102, 103, 104, 105, 106, 107, 108],
    
    "Name": [
        "Bhoomi", "Ayush", "Parth", "Payal",
        "Sonam", "Sanjeev", "Rahul", "Priya"
    ],
    
    "Age": [18, 19, 20, 21, 22, 20, 19, 18],
    
    "Course": [
        "CSE", "IT", "ECE", "ME",
        "CSE", "IT", "ECE", "CSE"
    ],
    
    "Salary": [
        25000, 30000, 28000, 26000,
        35000, 40000, 32000, 29000
    ]
})
fees = pd.DataFrame({
    "Student_ID": [101, 102, 103, 105, 107, 108],
    
    "Fee_Status": [
        "Paid", "Pending", "Paid",
        "Paid", "Pending", "Paid"
    ],
    
    "Scholarship": [
        5000, 0, 3000,
        4000, 0, 2000
    ]
})

In [45]:
students

   Student_ID     Name  Age Course  Salary
0         101   Bhoomi   18    CSE   25000
1         102    Ayush   19     IT   30000
2         103    Parth   20    ECE   28000
3         104    Payal   21     ME   26000
4         105    Sonam   22    CSE   35000
5         106  Sanjeev   20     IT   40000
6         107    Rahul   19    ECE   32000
7         108    Priya   18    CSE   29000

In [46]:
fees

   Student_ID Fee_Status  Scholarship
0         101       Paid         5000
1         102    Pending            0
2         103       Paid         3000
3         105       Paid         4000
4         107    Pending            0
5         108       Paid         2000

In [47]:
pd.merge(students,fees)

   Student_ID    Name  Age Course  Salary Fee_Status  Scholarship
0         101  Bhoomi   18    CSE   25000       Paid         5000
1         102   Ayush   19     IT   30000    Pending            0
2         103   Parth   20    ECE   28000       Paid         3000
3         105   Sonam   22    CSE   35000       Paid         4000
4         107   Rahul   19    ECE   32000    Pending            0
5         108   Priya   18    CSE   29000       Paid         2000

In [49]:
pd.merge(students,fees,on = "Student_ID",how = "right")

   Student_ID    Name  Age Course  Salary Fee_Status  Scholarship
0         101  Bhoomi   18    CSE   25000       Paid         5000
1         102   Ayush   19     IT   30000    Pending            0
2         103   Parth   20    ECE   28000       Paid         3000
3         105   Sonam   22    CSE   35000       Paid         4000
4         107   Rahul   19    ECE   32000    Pending            0
5         108   Priya   18    CSE   29000       Paid         2000

In [50]:
pd.merge(students,fees,on = "Student_ID",how = "outer")

   Student_ID     Name  Age Course  Salary Fee_Status  Scholarship
0         101   Bhoomi   18    CSE   25000       Paid       5000.0
1         102    Ayush   19     IT   30000    Pending          0.0
2         103    Parth   20    ECE   28000       Paid       3000.0
3         104    Payal   21     ME   26000        NaN          NaN
4         105    Sonam   22    CSE   35000       Paid       4000.0
5         106  Sanjeev   20     IT   40000        NaN          NaN
6         107    Rahul   19    ECE   32000    Pending          0.0
7         108    Priya   18    CSE   29000       Paid       2000.0

In [51]:
data = {
    "Category": ["A", "A", "B", "B", "A", "B"],
    "Shop": ["S1", "S2", "S1", "S2", "S1", "S2"],
    "Sales": [500, 700, 300, 900, 400, 600]
}


df = pd.DataFrame(data)
df

  Category Shop  Sales
0        A   S1    500
1        A   S2    700
2        B   S1    300
3        B   S2    900
4        A   S1    400
5        B   S2    600

In [52]:
df.groupby("Category")

In [53]:
df.groupby("Category")["Sales"].sum()

Category
A    1600
B    1800
Name: Sales, dtype: int64

In [54]:
df.groupby("Shop")["Sales"].sum()

Shop
S1    1200
S2    2200
Name: Sales, dtype: int64

In [55]:
df.groupby(["Category","Shop"])["Sales"].sum()

Category  Shop
A         S1       900
          S2       700
B         S1       300
          S2      1500
Name: Sales, dtype: int64

In [56]:
df

  Category Shop  Sales
0        A   S1    500
1        A   S2    700
2        B   S1    300
3        B   S2    900
4        A   S1    400
5        B   S2    600

In [57]:
df["Sales"].mean()

np.float64(566.6666666666666)

In [58]:
df["Sales"].agg(["mean","median","max","min","count"])

mean      566.666667
median    550.000000
max       900.000000
min       300.000000
count       6.000000
Name: Sales, dtype: float64